# Generated by Django 4.0.2 on 2022-04-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsToday', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
