# Generated by Django 4.0.2 on 2022-04-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsToday', '0003_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=255)),
                ('news_content', models.TextField()),
                ('news_image', models.ImageField(upload_to='news')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NewsToday.category')),
            ],
        ),
    ]
