# Generated by Django 4.0.2 on 2022-04-26 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsToday', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 4, 26, 3, 56, 36, 14239, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(verbose_name=999999999999),
        ),
    ]
