# Generated by Django 4.0.2 on 2022-04-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsToday', '0006_news_date_posted_news_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NewsToday.category')),
            ],
        ),
    ]
